### ISSUE TITLE
dev-php/pecl-pthreads-3.1.6 trying to install non-existent README.API 

### ISSUE THREAD

**Issue by ghost** [fmoro/faustoo#6]
As in description, README.API appears not present in sources. ebuild explicitly sets this DOC for intallation. README.md is present, instead

**Comment by ghost** [comment]
>>> Install pecl-pthreads-3.1.6 into /var/tmp/portage/dev-php/pecl-pthreads-3.1.6/image/ category dev-php
make -j8 install-headers 
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'README.API'
 * ERROR: dev-php/pecl-pthreads-3.1.6::php-kit failed (install phase):
 *   dodoc failed
 *

**Comment by ghost** [comment]
thanks :)
